[project]
name = "matchbox"
description = "A web app version of the ODT cRF calculator"
readme = "README.md"
license = "MIT"
dynamic = ["version"]

[tool.ruff]
line-length = 120
extend-select = ["I"]
