name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: # Add this section
  contents: read # write - Needed to checkout the code
  packages: write # Needed to push to GHCR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ""
          script: |                       
            cd /home/oxfordgenes/matchbox   # Change this to the directory on the server where your docker-compose.yml is stored
            docker-compose pull             # Pull the latest image
            docker-compose down             # Stop and remove any existing containers
            docker-compose up -d            # Start the services in detached mode